name: Upload and publish to Chrome Web Store

on:
  push:
    tags:
      - v*

jobs:
  upload-and-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: zip app.zip background.js browser_action.js icon128.png manifest.json popup.html
      - run: |
          ACCESS_TOKEN=$(curl -X POST https://oauth2.googleapis.com/token -d \
            "client_id=$CHROME_WEB_STORE_CLIENT_ID&client_secret=$CHROME_WEB_STORE_CLIENT_SECRET&refresh_token=$CHROME_WEB_STORE_REFRESH_TOKEN&grant_type=refresh_token" \
            | jq '.access_token' -r)

          curl \
            -H "Authorization: Bearer $ACCESS_TOKEN"  \
            -H "x-goog-api-version: 2" \
            -X PUT \
            -T app.zip \
            https://www.googleapis.com/upload/chromewebstore/v1.1/items/$CHROME_WEB_STORE_APP_ID

          curl \
            -H "Authorization: Bearer $ACCESS_TOKEN"  \
            -H "x-goog-api-version: 2" \
            -H "Content-Length: 0" \
            -H "Expect:" \
            -X GET \
            https://www.googleapis.com/chromewebstore/v1.1/items/$CHROME_WEB_STORE_APP_ID?projection=draft

          curl \
            -H "Authorization: Bearer $ACCESS_TOKEN"  \
            -H "x-goog-api-version: 2" \
            -H "Content-Length: 0" \
            -X POST \
            https://www.googleapis.com/chromewebstore/v1.1/items/$CHROME_WEB_STORE_APP_ID/publish

